### ISSUE TITLE
Option to preserve whitespace in the beginning and end of tag data

### ISSUE THREAD

**Issue by sumeetdas** [jhuckaby/pixl-xml#10]
I liked the library. Unfortunately, I could not see any option to preserve any whitespace in the beginning and the end of tag data. This is very important for my project and hence would request you to add this option. I can even implement it myself if you allow me to. Thanks!

**Comment by jhuckaby** [comment]
Should be fixed in [v1.0.11](https://github.com/jhuckaby/pixl-xml/releases/tag/v1.0.11).

### preserveWhitespace

If you want to preserve whitespace before and after text inside elements, set the `preserveWhitespace` flag to a true value.  Note that this has no effect on attributes (whitespace is always preserved there), nor does it effect whitespace *between* complex elements.  Example:

```js
var xml_string = '<?xml version="1.0"?> <Document> ' + 
	' <Simple>  Hello  </Simple> ' + 
	' <Node Key="  Value  ">  Complex  </Node> ' + 
	' </Document> ';

var doc = XML.parse( xml_string, { preserveWhitespace: true } );
console.log( doc );
```

With the `preserveWhitespace` flag set to true, this would produce the following object:

```js
{
	"Simple": "  Hello  ",
	"Node": {
		"Key": "  Value  ",
		"_Data": "  Complex  "
	}
}
```

Notice that the whitespace before/after all the opening and closing tags has no effect on the parsed object.  It only has effect *inside* elements that also contain a text value.
