### ISSUE TITLE
Fails to Parse HTML

### ISSUE THREAD

**Issue by martindale** [jhuckaby/pixl-xml#17]
Input:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Sample Data</title>
  </head>
  <body>
    <h1>This is a test of <code>pixl-xml</code>!</h1>
  </body>
</html>
```
Generates:
```
Error: Parse Error: Malformed DTD tag on line 1: <!DOCTYPE html>
```

**Comment by jhuckaby** [comment]
I do apologize, but this library really isn't designed to parse HTML.  It is only designed for XML.  HTML is very complex and difficult to parse into an object/array structure.

Even if your HTML didn't have the DTD line, the library would still choke on things like this:

```html
<h1>This is a test of <code>pixl-xml</code>!</h1>
```

The reason is you have a mixed element with both plain text and child nodes at the same level.  pixl-xml's simplified object/array structure cannot represent this type of complex document, so it kinda falls over.

Also, HTML's elements that don't need to be closed, e.g. `<img src="yo.jpg">`, and attributes without quotes, e.g. `<img src=yo.jpg>` cause it to totally choke and fail.

Sorry :(
